[workspace]
members = [
    "simd-minimizers",
    "simd-minimizers-bench",
]
resolver = "2"

[profile.release]
lto = "thin"
incremental = true
debug = true

[workspace.dependencies]
packed-seq = "1.0.1"
