name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --package simd-minimizers
      - name: Run tests
        run: cargo test --verbose --package simd-minimizers

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --package simd-minimizers
      - name: Run tests
        run: cargo test --verbose --package simd-minimizers
